{
	"name": "",
	"desc_short": null,
	"desc_long": "支持iOS 12和13<br>Arc為您帶來了一種全新的方式來快速訪問您最常使用的操作<br>它的時尚菜單可以隨時隨地從iOS中的任何位置拉出，只需從您選擇將其定位在屏幕的角上拉起即可<br>適合任何設置<br>Arc的快速訪問，簡潔的設計使其可以完美地適合任何設置，並且其自定義選項可讓您對其進行修改，以使其外觀和功能完全符合您的期望<br><br>Arc提供了多種動作供您選擇，包括：<br>應用啟動器<br>硬件按鍵<br>CC，NC，Siri，App切換器等<br>屏幕截圖<br>媒體控件（播放/暫停）<br>更多<br><br>通過調整多種樣式和功能選項的功能，Arc提供了您所需的一切，以使其完全適應您的喜好<br><br>Arc brings you a brand new way to quickly access the actions you use the most.<br>Its sleek menu can be pulled up at any time, from anywhere in iOS, by simply pulling up from the corner of the screen that you've chosen to position it at.<br><br>Fits any setup<br>Arc's quick-access, unobtrusive design allows it to fit perfectly with any setup, and its customisation options will let you modify it to look and function exactly how you'd like it to.<br><br>Fully customizable<br>Arc comes with a wide range of actions to choose between, including:<br>App launchers<br>Hardware buttons<br>CC, NC, Siri, App switcher, etc.<br>Screenshot, previous app<br>Media controls (play/pause)<br>And more!<br><br>With the ability to adjust multiple style and functionality options, Arc comes with everything you need to fully adapt it to your preference.",
	"compatitle": "iOS 12-13",
	"changelog": "<strong>1.0.4</strong><br>- Initial Release.<br>",
	"screenshot": "<div style='text-align:center;'><img width=95% src='https://i.imgur.com/aCllybK.png;'><div style='text-align:center;'><img width=95% src='https://i.imgur.com/jE5VkHA.png;'><div style='text-align:center;'><img width=95% src='https://i.imgur.com/EPjpgwD.png;'><div style='text-align:center;'><img width=95% src='https://i.imgur.com/pT2l3VW.png;'/></a><br></div>",
	"notes": "如您在本源下載任何插件提示收費或遇到收費才能下載，請先安裝本源的SwipeForMore插件，然後找到你要下載的插件，左滑安裝即可，不要點進去下載！由於本源大部分插件為正版，所以會提示這種現象！<br><br>If the system prompts that you need to pay money to download Tweaks from this source, or there is a payment sign on the right side of Tweaks, please install SwipeForMore Tweak in Repo, then find the Tweaks to download, and then swipe left to install, please do not directly click download!  Or click on Videos below to view the download method.  Since most of the plugins in this Repo are genuine, this phenomenon will be prompted!",
	"open": true,
}